# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40f59abda5937600e8cd0848304b08c2a10b9a32b303e6957021eee4373b93416d2f1e419c46e56bf2205c192b1ddf100bcc8ea84f0b0ee6196c75b499a0b1ba

test:
  secret_key_base: c972efe5927dde59fff7a8c2dc6917a4cee85dffc6471ab91ae5eff4fd9ecfe5bdf36f0bdea73ea62337785a6e6c9c2b5e282b8840f757f0b884551e1173c3ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
